sudo: false

language: php
php:
 - 7.0

before_script:
 - phpenv config-rm xdebug.ini
 - pecl install channel://pecl.php.net/pthreads-3.1.6
 - pecl install channel://pecl.php.net/weakref-0.3.2
 - echo | pecl install channel://pecl.php.net/yaml-2.0.0RC7

script:
 - ./tests/ci.sh

#notifications:
  #email: false
